#!/usr/bin/env bash
# This script tells a story based on the content of the /etc/passwd file

# Using a while loop to read lines from /etc/passwd
while IFS=: read -r username passwd uid gid gecos home shell
do
    echo "The user $username is part of the $gid gang, lives in $home and rides $shell. $uid's place is protected by the passcode $passwd, more info about the user here: $gecos"
done < /etc/passwd
